### ISSUE TITLE
Warning with curl_setop() with facebook

### ISSUE THREAD

**Issue by lonchbox** [33themes/ttt-social#1]
Using the debug bar I got this Warning:
`WARNING: wp-content/plugins/ttt-social-master/class/TTTSocial_Common.php:140 - curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/longsocial/single.php'), get_template_part, locate_template, load_template, require('/themes/longsocial/parts/template-formats.php'), get_sidebar, locate_template, load_template, require_once('/themes/longsocial/sidebar.php'), dynamic_sidebar, call_user_func_array, WP_Widget->display_callback, TTTSocial_vimeo_widget->widget, TTTSocial_Common->vimeo_load, curl_setopt`
And it doesn´t display the facebook feed

**Comment by gabrielperezs** [comment]
The RSS feed of facebook don't exits any more :)
